[package]
name = "overlay-projects"
version = "0.1.0"
authors = ["hashmimic <hashmimic1@gmail.com>"]
edition = "2021"
license = "MPL-2.0"

[features]
default = ["std"]
std = ["concordium-std/std"]

[dependencies]
concordium-std = "6.1.0"

[lib]
crate-type=["cdylib", "rlib"]
